#!/usr/bin/env bash

LOG_FILE=~/.start-polybar.out

function getPrimaryMonitor() {
	PRIMARY_MONITOR=$(xrandr -q |grep -P '(?<!disconnected\s)primary' |awk '{print $1}')
	#If our primary monitor is disconnected, use the first connected monitor.
	if [[ -z $PRIMARY_MONITOR ]]; then
		echo $(xrandr -q |grep -P '(?<!dis)connected' |awk '{print $1}' |head -n 1)
	else
		echo $PRIMARY_MONITOR
	fi
}

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
PRIMARY_MONITOR=$(getPrimaryMonitor)
OTHER_MONITORS=$(xrandr -q |grep -P '(?<!dis)connected\s(?!primary)' |awk '{print $1}' |grep -v "^$PRIMARY_MONITOR$")

export DPI=$(xfconf-query -c xsettings -p /Xft/DPI)
MONITOR=$PRIMARY_MONITOR nohup polybar primary 2>&1 >> $LOG_FILE &
echo "$OTHER_MONITORS" |while read monitor; do
	if [[ ! -z $monitor ]]; then
		MONITOR=$monitor nohup polybar secondary 2>&1 >> $LOG_FILE &
	fi
done
