#!/usr/bin/env python3
import sys
import i3

newWorkspace = sys.argv[1]
workspaces = i3.get_workspaces()
workspacesWithName = [workspace for workspace in workspaces
                      if workspace["name"] == newWorkspace]

if len(workspacesWithName) == 0:
    raise ValueError(f"Workspace {newWorkspace} not found")

# i3 will only allow one workspace to have a name at a time.
newWorkspaceMonitor = workspacesWithName[0]["output"]

for workspace in workspaces:
    if workspace["focused"]:
        oldWorkspaceMonitor = workspace["output"]
        if newWorkspaceMonitor != oldWorkspaceMonitor:
            i3.command(f"[workspace={newWorkspace}] move workspace",
                       f"to output {workspace['output']}")
            i3.command(f"[workspace={workspace['name']}] move workspace",
                       f"to output {newWorkspaceMonitor}")
            # Prevent i3 from creating a new workspace during the swap process
            i3.command(f"[workspace={newWorkspace}] focus")
            i3.command(f"[workspace={workspace['name']}] focus")
        i3.command("rename workspace", f"{workspace['name']} to temp")
        i3.command("rename workspace", f"{newWorkspace} to {workspace['name']}")
        i3.command("rename workspace", f"temp to {newWorkspace}")
        break
